name: Haskell CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 120

    env:
      GHC_VERSION: "9.4.5"

    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.nixos.org/

      - name: Check Cachix token exists
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"
        run: |
          if [[ -z "$CACHIX_AUTH_TOKEN" ]]; then
              echo "Must provide CACHIX_AUTH_TOKEN in environment" 1>&2
              exit 1
          fi

      - name: Setup cachix cache
        uses: cachix/cachix-action@v12
        with:
          name: myopia
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: true # push isn't supported for flake based setups: https://github.com/cachix/cachix-action/issues/47

      - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ env.GHC_VERSION }}-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
          restore-keys: ${{ runner.os }}-${{ env.GHC_VERSION }}-

      - name: Check nix environment
        run: |
          set -x

          nix flake check
          nix run .#check-formatting

      - name: Check Haskell formatting
        run: |
          set -x
          nix develop -c fourmolu --mode check $(find -type f -name "*.hs" -not -path "*/dist-newstyle/*")

      - name: Build
        run: |
          nix develop -c cabal build

      - name: Run tests
        run: nix develop -c cabal test
